# Generated by Django 3.1 on 2020-09-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
