# Generated by Django 3.1 on 2020-09-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='coffee.jpg', null=True, upload_to=''),
        ),
    ]
